sudo: required
services:
  - docker

before_install:
  - docker build -t hunkevych-philip/docker-kubernetes -f Dockerfile.dev .

script:
  - docker run hunkevych-philip/docker-kubernetes go test -cover ./...
