version: '3.3'
services:
  test:
    build: .
    command:
      - "go"
      - "test"
      - "./..."
  redis-service:
    image: 'redis'
  go-app:
    restart: 'always'
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./cmd/volumes:/usr/src/app/cmd/volumes
